### ISSUE TITLE
Could you please create 64bit version?

### ISSUE THREAD

**Issue by TThana** [mobi-life/sqlitere#1]
Could you please create 64bit version?
for
arm64-v8a,x86_64

**Comment by mobi-life** [comment]
Hi TThana,

Do you mean compiled outputs for "arm64-v8a,x86_64" ?

**Comment by TThana** [comment]
yes, how to create the output for "arm64-v8a,x86_64" ?

**Comment by mobi-life** [comment]
in the file ` /src/main/jni/Application.mk ` change the line 18 from ` APP_ABI := armeabi armeabi-v7a x86`  to   **`APP_ABI := AArch64 x86-64`**  and then try to compile again.

**Comment by TThana** [comment]
Thank you very much for the suggestion.
